name: doctor_panel
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.16
  shimmer: ^3.0.0

  # Localization & Formatting
  intl: ^0.20.1

  # Navigation
  go_router: ^14.6.2

  # State Management & Dependency Injection
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  get_it: ^8.0.3

  # Storage & Caching
  shared_preferences: ^2.3.3

  # Networking & API Calls
  http: ^1.3.0

  # Media & File Handling
  image_picker: ^1.1.2

  # UI Components
  dropdown_button2: ^2.3.9
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Inter
      fonts:
         - asset: assets/fonts/Inter_Light.ttf
           weight: 300
         - asset: assets/fonts/Inter_Regular.ttf
           weight: 400
         - asset: assets/fonts/Inter_Medium.ttf
           weight: 500
         - asset: assets/fonts/Inter_SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Inter_Bold.ttf
           weight: 700
         - asset: assets/fonts/Inter_Bold.ttf
           weight: 800